app = "cookware"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[processes]
  web = "bash -c 'cd apps/api && node dist/index.js'"
  ingester = "bash -c 'cd apps/ingester && node dist/index.js'"

[deploy]
  release_command = "bash -c 'cd libs/database && pnpm db:migrate'"

[[vm]]
  size = "shared-cpu-1x"
  memory = 256
  processes = ["web"]

[[vm]]
  size = "shared-cpu-1x"
  memory = 256
  processes = ["ingester"]

[[services]]
  http_checks = []
  processes = ["web"]
  internal_port = 8080
    [[services.ports]]
      handlers = ["http"]
      port = 80
      force_https = true
    [[services.ports]]
      handlers = ["tls", "http"]
      port = 443

[[statics]]
  guest_path = "/usr/src/app/apps/web/dist/assets"
  url_prefix = "/assets"
