app = "cookware"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[processes]
web "cd apps/api && node dist/index.js"
ingester = "cd apps/ingester && node dist/index.js"

[[vm]]
size = "shared-cpu-1x"
memory = 256
processes = ["web"]

[[vm]]
size = "shared-cpu-1x"
memory = 256
processes = ["ingester"]

[[services]]
  http_checks = []
  internal_port = 8080
    [[services.ports]]
      handlers = ["http"]
      port = 80
      force_https = true
    [[services.ports]]
      handlers = ["tls", "http"]
      port = 443
